<?xml version="1.0"?>
<project
		xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd"
		xmlns="http://maven.apache.org/POM/4.0.0"
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>software.xdev.tci.demo</groupId>
		<artifactId>advanced-demo</artifactId>
		<version>4.3.1-SNAPSHOT</version>
	</parent>
	<artifactId>entities-metamodel</artifactId>

	<properties>
		<!-- Ignore auto generated code -->
		<sonar.exclusions>
			src/gen/java/**
		</sonar.exclusions>
	</properties>

	<dependencies>
		<dependency>
			<groupId>software.xdev.tci.demo</groupId>
			<artifactId>entities</artifactId>
		</dependency>
	</dependencies>

	<build>
		<sourceDirectory>${project.basedir}/src/gen/java/</sourceDirectory>
	</build>
</project>
