name: Run OIDC Server Mock integration tests

on:
  workflow_dispatch:
  push:
    branches: [ develop ]
    paths: 
      - 'oidc-server-mock/**'
  pull_request:
    branches: [ develop ]
    paths: 
      - 'oidc-server-mock/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  oidc-server-mock:
    uses: ./.github/workflows/run-module-integration-tests.yml
    with:
      module: oidc-server-mock
    secrets: inherit
